version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: minimalist-postgres
    volumes:
      - minimalist-psql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: minimalist-backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DB_URL=postgres://postgres:docker@minimalist-postgres:5432/postgres
      - PORT=3000
      - TWILIO_ACCOUNT_SID=ACa1f747e5cf0c5424e1ff7cb4724308c3
      - TWILIO_SERVICE_SID=VAbce17841c3cef26fa19797e901527758
      - TWILIO_AUTH_TOKEN=5b76ede3eff1fca9c5ad0e6901784c90

volumes:
  minimalist-psql:
